### ISSUE TITLE
Add BundleIdentifier to Application struct

### ISSUE THREAD

**Issue by thorstenstark** [tbointeractive/bytes#37]
We should add the bundle identifier to the Application struct. 
Additionally I would suggest to modify the descriptions of the properties to include the used Key to retrieve a value from the bundle. That would prevent some accidental misuses.

**Comment by brototyp** [comment]
What do you mean by bundle identifier? The `CFBundleName`? Or something different?

I like the idea to adding some details to the documentation!

**Comment by thorstenstark** [comment]
No, I mean `CFBundleIdentifier` ;)

**Comment by brototyp** [comment]
Ah yeah, got it. Just out of curiosity: What would be the use case to access this via the `Application`?

**Comment by thorstenstark** [comment]
Do you think that would not fit here? I would say it has the same use case as `Application.name` or `Application.displayName`.

**Comment by brototyp** [comment]
> Do you think that would not fit here? I would say it has the same use case as `Application.name` or `Application.displayName`.

No, don't get me wrong. I think it fits perfectly. I am just curious how you thought about adding it and if you possibly already have a use case in mind.

**Comment by thorstenstark** [comment]
I see. We needed to access the bundle identifier lately and a collegue misused `Application.name` for it because the documentation looked like it would return the bundle identifier (but didn't).
