### ISSUE TITLE
Add priority to LayoutConstraint methods

### ISSUE THREAD

**Issue by thorstenstark** [tbointeractive/bytes#45]
# Example
## now:
`@objc @discardableResult func constrainEqual(attribute: NSLayoutConstraint.Attribute, to constant: CGFloat) -> NSLayoutConstraint `

## new:
`@objc @discardableResult func constrainEqual(attribute: NSLayoutConstraint.Attribute, to constant: CGFloat, priority: UILayoutPriority) -> NSLayoutConstraint `

**Comment by brototyp** [comment]
Nice! We did that in our implementation as well. We added a default parameter (`= .required`) to the priority to be backwards compatible.

**Comment by thorstenstark** [comment]
Yeah, I had the same idea, but forgot to add it here 😅
